---
title: "webscraping_dog_info"
author: "Kristen A, kkakey"
date: "11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(tidyverse)
library(RSelenium)
```

[Most popular dog breeds of 2020](https://www.akc.org/expert-advice/dog-breeds/the-most-popular-dog-breeds-of-2020/)

Get rankings
```{r}
page <- read_html('https://www.akc.org/expert-advice/dog-breeds/the-most-popular-dog-breeds-of-2020/')

table_rank <- page %>%
  html_nodes(xpath='//*[@id="main-content"]/div[1]/div[2]/div/div[1]/table') %>%
  html_table(fill = TRUE) 

table_rank <- table_rank %>%
  as.data.frame() %>%
  janitor::row_to_names(row_number=1)
```

Get links to dog breed information
```{r}
links <- page %>%
  html_nodes(xpath='//*[@id="main-content"]/div[1]/div[2]/div/div[1]/table') %>%
  html_nodes("tr") %>%
  html_nodes("a") %>% html_attr("href")

table_rank <- cbind(table_rank, links)
# write.csv(table_rank, "./output-data/table_rank_2020.csv")
```


Webscrape trait information, image links, and weight of all dog breeds
```{r}
df <- data.frame(matrix(ncol = 5, nrow = 0))
breed_img_full <- data.frame(matrix(ncol = 3, nrow = 0))

fprof <- getFirefoxProfile("/Users/kristenakey/Library/Application Support/Firefox/Profiles/gfsv23kr.default-release-1", useBase=TRUE)

for (num in seq_along(links)) {
  
  print(paste(num, table_rank[num,]$Breed))
  
  url <- links[num]
  if (num==1) {
    rD <- RSelenium::rsDriver(browser = "firefox", extraCapabilities = fprof, port = 4567L, verbose = T)
    remDr <- rD[["client"]]
  }
  remDr$navigate(url)
  Sys.sleep(10)
  
  html <- remDr$getPageSource()[[1]]
  
  ################
  c <- 1
  breed_table <- data.frame(matrix(ncol = 5, nrow = 0))
  while (c <17) {
    
    if (c==7) {
      # Coat Types
      trait <- "Coat Type"
      trait_range1 <- "-"
      trait_range2 <- "-"
      
      trait_score <- read_html(html) %>%
        html_nodes("div.breed-trait-group__trait-all") %>%
        .[[7]] %>% html_nodes("div.breed-trait-score__choices") %>% .[[1]] %>% 
        html_nodes("div.breed-trait-score__choice.breed-trait-score__choice--selected") %>%
        html_text()
    }
    
    else if (c==8) {
      # Coat Length
      trait <- "Coat Length"
      trait_range1 <- "-"
      trait_range2 <- "-"
      
      trait_score <- read_html(html) %>%
        html_nodes("div.breed-trait-group__trait-all") %>%
        .[[8]] %>% html_nodes("div.breed-trait-score__choices") %>% .[[1]] %>% 
        html_nodes("div.breed-trait-score__choice.breed-trait-score__choice--selected") %>%
        html_text()
    }
    
    else {
      # header for trait
      trait <- read_html(html) %>% 
        html_nodes("div.breed-trait-group__trait-all") %>%
          .[[c]] %>% html_nodes("h4") %>% html_text()
      
      # text of ranges
      trait_range <- read_html(html) %>%
        html_nodes("div.breed-trait-group__trait-all") %>%
        .[[c]] %>% html_nodes("div.breed-trait-score__score-label") %>% 
        html_nodes("span") %>% html_text()
      
      trait_range1 <- trait_range[1]
      trait_range2 <- trait_range[2]
      
      # number on scale (1-5)
      trait_score <- read_html(html) %>%
        html_nodes("div.breed-trait-group__trait-all") %>%
        .[[c]] %>% html_nodes("div.breed-trait-score__score-wrap") %>%
        html_nodes("div.breed-trait-score__score-unit.breed-trait-score__score-unit--filled") %>% 
        length()
      
    }
    c <- c + 1
    breed_table <- rbind(breed_table, c(table_rank[num,]$Breed, trait, 
                                        trait_range1, trait_range2, trait_score))
  }
  colnames(df)  <- c("Breed", "Trait", "Trait_1", "Trait_5", "Trait_Score")
  colnames(breed_table)  <- c("Breed", "Trait", "Trait_1", "Trait_5", "Trait_Score")
  df <- rbind(df, breed_table)
  ################
  
  ################
  breed_img_table <- data.frame(matrix(ncol = 3, nrow = 0))
  tryCatch(
    expr = {
          image_link <- read_html(html) %>% 
            html_nodes("div.breed-page__standard__image") %>% .[[1]] %>%
            html_nodes("img") %>%
            html_attr("data-src")
    },
    error = function(e){ 
        image_link <- read_html(html) %>% 
            html_nodes("div.breed-page__hero__gallery__image-wrapper") %>% .[[1]] %>%
            html_nodes("img") %>%
            html_attr("data-src")
    }
  )
  
  # text on weight
  text <- read_html(html) %>% 
    html_nodes("div.flex.flex-col") %>%
    html_nodes("p.f-16.my0.lh-solid.breed-page__hero__overview__subtitle")%>% html_text()
    
  weight <- text[grepl("pounds", text, fixed = TRUE)]

  breed_img_table <- rbind(breed_img_table, c(table_rank[num,]$Breed , 
                                              image_link, paste(weight,collapse = '; ')))
  colnames(breed_img_full)  <- c("Breed", "Image", "Weight")
  colnames(breed_img_table)  <- c("Breed", "Image", "Weight")
  breed_img_full <- rbind(breed_img_full, breed_img_table)
  ################
  
  Sys.sleep(runif(1, min = 3, max = 6))

}

# close webpage
rD$server$stop()

### save data
# write.csv(df, "./output-data/breed_traits.csv")
# write.csv(breed_img_full, "./output-data/breed_weight_image.csv")
```

Clean and join data
```{r}
breed_traits <- read_csv("./output-data/breed_traits.csv")
breed_weight_image <- read_csv("./output-data/breed_weight_image.csv")

# classify Size of dog based on weight
breed_weight_image$weight_cat <- ""
for (i in seq_along(breed_weight_image$Breed)) { 
      max_weight <- as.numeric(max(unlist(regmatches(breed_weight_image$Weight[i], 
                                                     gregexpr("[[:digit:]]+",
                                                      breed_weight_image$Weight[i])))))
      weight_cat <- case_when(
        max_weight <=35 ~ "small",
        max_weight > 35 & max_weight <=60 ~ "medium",
        max_weight > 60 & max_weight <=90 ~ "large",
        max_weight > 90 ~ "x-large"
      )
      
    breed_weight_image$weight_cat[i] <- weight_cat
}

# joined webscraped data
joined_data <- breed_traits %>%
  select(!X1) %>%
  left_join(., table_rank, on ="Breed") %>%
  rename(rank=`2020 Rank`) %>%
  left_join(., breed_weight_image %>% select(!X1), on ="Breed")

# write.csv(df, "./output-data/final-long.csv")
```

```{r}
# pivot to wide
df_wide <- pivot_wider(joined_data, 
            id_cols = c(rank, Breed),
            names_from = Trait, 
            values_from = Trait_Score) %>%
  distinct()

df_wide <- df_wide %>%
  left_join(., joined_data %>% select(Breed, Image, weight_cat), on="Breed") %>% distinct()

df_wide <- df_wide[,c(1,19,2,3:18,20)]
# write.csv(df_wide, "./output-data/df_wide.csv")
```

```{r}
# re-order and keep columns I want 
col_order <- c("rank", "Image", "Breed", "weight_cat",
               "Energy Level", "Trainability Level", 
               "Affectionate With Family","Good With Young Children","Good With Other Dogs", 
                "Openness To Strangers","Watchdog/Protective Nature", "Barking Level",
               "Shedding Level")
df_final <- df_wide[, col_order]
df_final <- df_final %>%
  rename(Size=weight_cat)

# manually add Sizes for those with NA
df_final[df_final$Breed=="Cane Corso", ]$Size <- "x-large"
df_final[df_final$Breed=="Spinoni Italiani" ,]$Size <- "large"
df_final[df_final$Breed=="Toy Fox Terriers" ,]$Size <- "small"
df_final[df_final$Breed=="Nederlandse Kooikerhondjes" ,]$Size <- "small"
df_final[df_final$Breed=="Plott Hounds" ,]$Size <- "medium"

# write.csv(df_final, "./df_final_for_table.csv")
```


